site_name: TACTIC Developer Docs
site_url: http://community.southpawtech.com

nav:
    - Introduction: './index.md'
    - Developer Start-up:
        - 'Development Concepts': './development-concepts.md'
        - 'Architecture Overview': './architecture-overview.md'
        - 'Tactic Script Editor': './tactic-script-editor.md'
        - 'Setting Up Dev Environment': './setting-up-dev-environment.md'
        - 'Watch Folder Service': './watch-folder-service.md'
    - Client API:
        - 'Setup': './client-api-setup.md'
        - 'Structure': './client-api-structure.md'
    - Examples:
        - 'Basic': './client-api-basic.md'
        - 'Checkin': './client-api-checkin.md'
        - 'Dependency': './client-api-dependency.md'
        - 'Expressions': './using-expressions-in-scripting.md'
        - 'Custom Widget Basics': './custom-interfaces-in-tactic.md'
        - 'Performance': './client-api-performance.md'
        - 'Hierarchy': './client-api-hierarchy.md'
    - Changes:
        - 'Search Id To Search Code': './search-id-to-search-code.md'
    - Custom Widgets:
        - 'Custom Layout Editor': './custom-layout-editor.md'
        - 'Widget Development': './widget-development.md'
        - 'Tactic Widgets': './tactic-widgets.md'
    - Plugins:
        - 'Plugin Manager Interface': './plugin-manager-interface.md'
        - 'Create A Plugin': './create-a-plugin.md'
        - 'Packaging A Plugin': './packaging-a-plugin.md'
        - 'Plugin Versions': './plugin-versions.md'
        - 'Packaging Python Scripts Into A Plugin': './packaging-python-scripts-into-a-plugin.md'
    - Validation:
        - 'Setup Validation': './setup-validation.md'
    - Async Loading:
        - 'Loading': './loading.md'
    - Messaging:
        - 'Messaging': './messaging.md'
    - Triggers:
        - 'Python Trigger In Tactic Editor Guideline': './python-trigger-in-tactic-editor-guideline.md'
        - 'Trigger': './trigger.md'
        - 'Setting Up The Schedule Event Trigger': './setting-up-the-schedule-event-trigger.md'
    - Check-ins:
        - 'Tactic Checkin Process': './tactic-checkin-process.md'
        - 'Custom Checkin Pipeline': './custom-checkin-pipeline.md'
    - Naming Conventions:
        - 'Naming Convention Classes': './naming-convention-classes.md'
    - API Reference:
        - 'List of methods': 'api_reference.md'
        - 'Init  ': './python-client-api_general___init__.md'
        - 'Get Protocol': './python-client-api_general_get_protocol.md'
        - 'Set Login Ticket': './python-client-api_general_set_login_ticket.md'
        - 'Set Project': './python-client-api_general_set_project.md'
        - 'Set Protocol': './python-client-api_general_set_protocol.md'
        - 'Set Server': './python-client-api_general_set_server.md'
        - 'Set Site': './python-client-api_general_set_site.md'
        - 'Abort': './python-client-api_general_abort.md'
        - 'Add Config Element': './python-client-api_general_add_config_element.md'
        - 'Add Dependency': './python-client-api_general_add_dependency.md'
        - 'Add Dependency By Code': './python-client-api_general_add_dependency_by_code.md'
        - 'Add Directory': './python-client-api_general_add_directory.md'
        - 'Add File': './python-client-api_general_add_file.md'
        - 'Add Group': './python-client-api_general_add_group.md'
        - 'Add Initial Tasks': './python-client-api_general_add_initial_tasks.md'
        - 'Build Search Key': './python-client-api_general_build_search_key.md'
        - 'Build Search Type': './python-client-api_general_build_search_type.md'
        - 'Check Access': './python-client-api_general_check_access.md'
        - 'Checkout': './python-client-api_general_checkout.md'
        - 'Clear Upload Dir': './python-client-api_general_clear_upload_dir.md'
        - 'Connect Sobjects': './python-client-api_general_connect_sobjects.md'
        - 'Create Note': './python-client-api_general_create_note.md'
        - 'Create Search Type': './python-client-api_general_create_search_type.md'
        - 'Create Snapshot': './python-client-api_general_create_snapshot.md'
        - 'Create Task': './python-client-api_general_create_task.md'
        - 'Delete Sobject': './python-client-api_general_delete_sobject.md'
        - 'Directory Checkin': './python-client-api_general_directory_checkin.md'
        - 'Download': './python-client-api_general_download.md'
        - 'Eval': './python-client-api_general_eval.md'
        - 'Execute Cmd': './python-client-api_general_execute_cmd.md'
        - 'Execute Js Script': './python-client-api_general_execute_js_script.md'
        - 'Execute Pipeline': './python-client-api_general_execute_pipeline.md'
        - 'Execute Python Script': './python-client-api_general_execute_python_script.md'
        - 'Finish': './python-client-api_general_finish.md'
        - 'Generate Ticket': './python-client-api_general_generate_ticket.md'
        - 'Get All Children': './python-client-api_general_get_all_children.md'
        - 'Get All Dependencies': './python-client-api_general_get_all_dependencies.md'
        - 'Get All Paths From Snapshot': './python-client-api_general_get_all_paths_from_snapshot.md'
        - 'Get Base Dirs': './python-client-api_general_get_base_dirs.md'
        - 'Get By Code': './python-client-api_general_get_by_code.md'
        - 'Get By Search Key': './python-client-api_general_get_by_search_key.md'
        - 'Get Child Types': './python-client-api_general_get_child_types.md'
        - 'Get Api Version': './python-client-api_general_get_client_api_version.md'
        - 'Get Client Dir': './python-client-api_general_get_client_dir.md'
        - 'Get Client Version': './python-client-api_general_get_client_version.md'
        - 'Get Column Info': './python-client-api_general_get_column_info.md'
        - 'Get Column Names': './python-client-api_general_get_column_names.md'
        - 'Get Config Definition': './python-client-api_general_get_config_definition.md'
        - 'Get Connected Sobject': './python-client-api_general_get_connected_sobject.md'
        - 'Get Connected Sobjects': './python-client-api_general_get_connected_sobjects.md'
        - 'Get Dependencies': './python-client-api_general_get_dependencies.md'
        - 'Get Expanded Paths From Snapshot': './python-client-api_general_get_expanded_paths_from_snapshot.md'
        - 'Get Full Snapshot Xml': './python-client-api_general_get_full_snapshot_xml.md'
        - 'Get Handoff Dir': './python-client-api_general_get_handoff_dir.md'
        - 'Get Home Dir': './python-client-api_general_get_home_dir.md'
        - 'Get Info From User': './python-client-api_general_get_info_from_user.md'
        - 'Get Input Tasks': './python-client-api_general_get_input_tasks.md'
        - 'Get Interaction Count': './python-client-api_general_get_interaction_count.md'
        - 'Get Md5 Info': './python-client-api_general_get_md5_info.md'
        - 'Get Message': './python-client-api_general_get_message.md'
        - 'Get Output Tasks': './python-client-api_general_get_output_tasks.md'
        - 'Get Parent': './python-client-api_general_get_parent.md'
        - 'Get Parent Type': './python-client-api_general_get_parent_type.md'
        - 'Get Path From Snapshot': './python-client-api_general_get_path_from_snapshot.md'
        - 'Get Paths': './python-client-api_general_get_paths.md'
        - 'Get Pipeline Processes': './python-client-api_general_get_pipeline_processes.md'
        - 'Get Pipeline Processes Info': './python-client-api_general_get_pipeline_processes_info.md'
        - 'Get Pipeline Xml': './python-client-api_general_get_pipeline_xml.md'
        - 'Get Pipeline Xml Info': './python-client-api_general_get_pipeline_xml_info.md'
        - 'Get Plugin Dir': './python-client-api_general_get_plugin_dir.md'
        - 'Get Preallocated Path': './python-client-api_general_get_preallocated_path.md'
        - 'Get Preference': './python-client-api_general_get_preference.md'
        - 'Get Related Types': './python-client-api_general_get_related_types.md'
        - 'Get Resource Path': './python-client-api_general_get_resource_path.md'
        - 'Get Server Api Version': './python-client-api_general_get_server_api_version.md'
        - 'Get Server Version': './python-client-api_general_get_server_version.md'
        - 'Get Snapshot': './python-client-api_general_get_snapshot.md'
        - 'Get Table Info': './python-client-api_general_get_table_info.md'
        - 'Get Ticket': './python-client-api_general_get_ticket.md'
        - 'Get Types From Instance': './python-client-api_general_get_types_from_instance.md'
        - 'Get Unique Sobject': './python-client-api_general_get_unique_sobject.md'
        - 'Get Virtual Snapshot Path': './python-client-api_general_get_virtual_snapshot_path.md'
        - 'Get Widget': './python-client-api_general_get_widget.md'
        - 'Group Checkin': './python-client-api_general_group_checkin.md'
        - 'Insert': './python-client-api_general_insert.md'
        - 'Insert Multiple': './python-client-api_general_insert_multiple.md'
        - 'Insert Update': './python-client-api_general_insert_update.md'
        - 'Log': './python-client-api_general_log.md'
        - 'Log Message': './python-client-api_general_log_message.md'
        - 'Query': './python-client-api_general_query.md'
        - 'Query Snapshots': './python-client-api_general_query_snapshots.md'
        - 'Reactivate Sobject': './python-client-api_general_reactivate_sobject.md'
        - 'Redo': './python-client-api_general_redo.md'
        - 'Retire Sobject': './python-client-api_general_retire_sobject.md'
        - 'Set Config Definition': './python-client-api_general_set_config_definition.md'
        - 'Set Current Snapshot': './python-client-api_general_set_current_snapshot.md'
        - 'Set Preference': './python-client-api_general_set_preference.md'
        - 'Set Widget Settings': './python-client-api_general_set_widget_settings.md'
        - 'Set Widget Settings': './python-client-api_general_set_widget_settings.md'
        - 'Simple Checkin': './python-client-api_general_simple_checkin.md'
        - 'Split Search Key': './python-client-api_general_split_search_key.md'
        - 'Start': './python-client-api_general_start.md'
        - 'Subscribe': './python-client-api_general_subscribe.md'
        - 'Undo': './python-client-api_general_undo.md'
        - 'Unsubscribe': './python-client-api_general_unsubscribe.md'
        - 'Update': './python-client-api_general_update.md'
        - 'Update Config': './python-client-api_general_update_config.md'
        - 'Update Multiple': './python-client-api_general_update_multiple.md'
        - 'Upload File': './python-client-api_general_upload_file.md'

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/favicon.ico
  features:
    -tabs
  font:
    text: Roboto
    code: Roboto Mono

highlightjs: true

#dev_addr: localhost:9000
dev_addr: 192.168.115.156:9000

extra_css:
    - css/extra.css

markdown_extensions:
    - attr_list
    - codehilite

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk


